import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"; // ✅ import toast

// Google fonts
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`
          min-h-screen bg-white text-gray-900 antialiased
          ${inter.variable} ${geistSans.variable} ${geistMono.variable}
        `}
      >
        {children}

        {/* ✅ Toast notifications container */}
        <Toaster
          position="top-right"      
          reverseOrder={false}      
          toastOptions={{
            duration: 4000,        
            style: {
              fontFamily: "var(--font-sans)", 
            },
          }}
        />
      </body>
    </html>
  );
}